-- 0079 — Disparo em massa (Broadcast) via WhatsApp Cloud API
CREATE TABLE IF NOT EXISTS `bychat_broadcast_campaigns` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(191) NOT NULL,
  `cloudApiConnectionId` INT NOT NULL,
  `templateId` INT NOT NULL,
  `templateName` VARCHAR(191) NOT NULL,
  `templateLanguage` VARCHAR(10) NOT NULL,
  `templateCategory` VARCHAR(30) NOT NULL,
  `variableMapping` JSON NOT NULL,
  `audienceType` VARCHAR(12) NOT NULL,
  `audienceMeta` JSON NULL,
  `status` VARCHAR(16) NOT NULL DEFAULT 'draft',
  `scheduledAt` DATETIME(3) NULL,
  `startedAt` DATETIME(3) NULL,
  `completedAt` DATETIME(3) NULL,
  `totalRecipients` INT NOT NULL DEFAULT 0,
  `sentCount` INT NOT NULL DEFAULT 0,
  `failedCount` INT NOT NULL DEFAULT 0,
  `skippedCount` INT NOT NULL DEFAULT 0,
  `createdByUserId` INT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `idx_bc_status` (`status`),
  KEY `idx_bc_sched` (`scheduledAt`),
  KEY `idx_bc_conn` (`cloudApiConnectionId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `bychat_broadcast_recipients` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `campaignId` INT NOT NULL,
  `leadId` INT NULL,
  `phone` VARCHAR(30) NOT NULL,
  `name` VARCHAR(191) NULL,
  `variables` JSON NOT NULL,
  `status` VARCHAR(12) NOT NULL DEFAULT 'pending',
  `skipReason` VARCHAR(30) NULL,
  `wamid` VARCHAR(191) NULL,
  `error` VARCHAR(500) NULL,
  `queuedAt` DATETIME(3) NULL,
  `sentAt` DATETIME(3) NULL,
  `deliveredAt` DATETIME(3) NULL,
  `readAt` DATETIME(3) NULL,
  `failedAt` DATETIME(3) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `idx_br_camp_status` (`campaignId`, `status`),
  KEY `idx_br_wamid` (`wamid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
