// components/ui/sets/names.ts
//
// Vocabulário de ícones do painel: os nomes que as telas usam. Cada set
// (`sets/lucide.ts`, `sets/tabler.tsx`, …) precisa cobrir esta lista inteira —
// se faltar um, o TypeScript reclama antes de virar círculo vazio na tela.
//
// Os nomes são os do lucide por herança histórica; o que importa é serem
// estáveis, porque é por eles que as telas pedem o ícone.

export const ICON_NAMES = [
  'LayoutDashboard',
  'Headphones',
  'MessageSquare',
  'Sparkles',
  'Users',
  'KanbanSquare',
  'GitFork',
  'ListChecks',
  'Tag',
  'FormInput',
  'Bot',
  'Globe',
  'Megaphone',
  'BrainCircuit',
  'Search',
  'FileText',
  'Link2',
  'Compass',
  'Activity',
  'Radar',
  'Target',
  'TrendingUp',
  'BarChart3',
  'Download',
  'LineChart',
  'FileSpreadsheet',
  'Workflow',
  'Phone',
  'Cloud',
  'Send',
  'Instagram',
  'Plug',
  'Boxes',
  'Handshake',
  'Settings',
  'GanttChart',
  'GraduationCap',
  'Layers',
  'Building2',
  'MapPin',
  'BookOpen',
  'CalendarRange',
  'FileCheck2',
  'ClipboardList',
  'School',
  'Award',
  'CreditCard',
  'ShieldCheck',
  'Trash2',
  'Server',
  'Map',
  'Sun',
  'Mail',
  'Brain',
  'Webhook',
  'Key',
  'Wrench',
  'Copy',
  'Clock',
  'XCircle',
  'Database',
  'Upload',
  'LifeBuoy',
  'Mic',
  'BookUser',

  // Vocabulário vindo dos menus dos tenants: ineprotec (jurídico),
  // elementus (clínica) e severiano já pediam estes nomes. Sem eles no
  // registry o menu do tenant não compila — o tipo é a barreira.
  'Archive',
  'Briefcase',
  'FileSignature',
  'Gavel',
  'HeartPulse',
  'Inbox',
  'PenLine',
  'Repeat',
  'ScrollText',
  'ShieldAlert',
  'Stethoscope',
  'TrendingDown',
  'Wallet',
] as const

export type IconName = (typeof ICON_NAMES)[number]
