// components/ui/sets/tabler.tsx
//
// Registry do menu. NÃO redesenha nada: reaproveita os mesmos componentes que
// as telas usam (`components/ui/icon-set.tsx`), para que um conceito tenha um
// desenho só no sistema inteiro.
//
// Antes deste arquivo existir assim, o menu e as telas tinham mapas separados —
// e "Conversas" aparecia com balão redondo no menu e quadrado na tela.

import type { IconName } from './names'
import { Instagram } from '../icons.custom'
import {
  LayoutDashboard,
  Headphones,
  MessageSquare,
  Sparkles,
  Users,
  KanbanSquare,
  GitFork,
  ListChecks,
  Tag,
  FormInput,
  Bot,
  Globe,
  Megaphone,
  BrainCircuit,
  Search,
  FileText,
  Link2,
  Compass,
  Activity,
  Radar,
  Target,
  TrendingUp,
  BarChart3,
  Download,
  LineChart,
  FileSpreadsheet,
  Workflow,
  Phone,
  Cloud,
  Send,
  Plug,
  Boxes,
  Handshake,
  Settings,
  GanttChart,
  GraduationCap,
  Layers,
  Building2,
  MapPin,
  BookOpen,
  CalendarRange,
  FileCheck2,
  ClipboardList,
  School,
  Award,
  CreditCard,
  ShieldCheck,
  Trash2,
  Server,
  Map,
  Sun,
  Mail,
  Brain,
  Webhook,
  Key,
  Wrench,
  Copy,
  Clock,
  XCircle,
  Database,
  Upload,
  LifeBuoy,
  Mic,
  BookUser,
  Archive,
  Briefcase,
  Inbox,
  Repeat,
  ScrollText,
  ShieldAlert,
  TrendingDown,
  Wallet,
  Scale,
  Pencil,
} from '../icon-set'

export const TABLER_ICONS: Record<IconName, unknown> = {
  Archive,
  Briefcase,
  Inbox,
  Repeat,
  ScrollText,
  ShieldAlert,
  TrendingDown,
  Wallet,
  // Sem desenho próprio no set: apelidam o vizinho mais próximo, do MESMO
  // set, para o menu não cair em círculo vazio. Desenhar os cinco à mão sem
  // poder conferir o traço sairia pior — quando o set for regerado, eles
  // ganham o desenho certo e estas linhas somem.
  Gavel: Scale,
  FileSignature: FileText,
  HeartPulse: Activity,
  Stethoscope: Activity,
  PenLine: Pencil,
  LayoutDashboard,
  Headphones,
  MessageSquare,
  Sparkles,
  Users,
  KanbanSquare,
  GitFork,
  ListChecks,
  Tag,
  FormInput,
  Bot,
  Globe,
  Megaphone,
  BrainCircuit,
  Search,
  FileText,
  Link2,
  Compass,
  Activity,
  Radar,
  Target,
  TrendingUp,
  BarChart3,
  Download,
  LineChart,
  FileSpreadsheet,
  Workflow,
  Phone,
  Cloud,
  Send,
  Plug,
  Boxes,
  Handshake,
  Settings,
  GanttChart,
  GraduationCap,
  Layers,
  Building2,
  MapPin,
  BookOpen,
  CalendarRange,
  FileCheck2,
  ClipboardList,
  School,
  Award,
  CreditCard,
  ShieldCheck,
  Trash2,
  Server,
  Map,
  Sun,
  Mail,
  Brain,
  Webhook,
  Key,
  Wrench,
  Copy,
  Clock,
  XCircle,
  Database,
  Upload,
  LifeBuoy,
  Mic,
  BookUser,
  Instagram,
}
